### ISSUE TITLE
Improper error message when JWT token is expired on /v1.4/{deviceId}/upload_url?path={path}

### ISSUE THREAD

**Issue by devtekve** [MoreTore/connect-killer#4]
When a JWT token is expired and a call is made to `/v1.4/{deviceId}/upload_url?path={path}` the endpoint returns a `200` with HTML code taking you to sign in with GitHub as if it was UserAdmin. This is not the expected behavior for an API and it should instead return a `401` https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

**Comment by MoreTore** [comment]
Should be fixed by https://github.com/MoreTore/connect-killer/commit/ccda6246fb101c3b029d759f7ee9ae783f969c59
