### ISSUE TITLE
Errors when pairing / unpairing

### ISSUE THREAD

**Issue by devtekve** [MoreTore/connect-killer#5]
I don't have useful screenshots at the moment. But when you pair or unpair, it throws an errors, however, it does succeed on both operations, but you must refresh the page to see that it paired, and you must sign out and sign back in to see it unpaired

**Comment by MoreTore** [comment]
thanks for the reminder. I think it has something to do with the server response

**Comment by MoreTore** [comment]
fixed https://github.com/MoreTore/connect-killer/commit/e5766c8c05d59a6d7b4ddaafd23f089dde02fa7f
